export const JOB_CATEGORIES = {
    "Accounts, Finance, Admin & HR": [
        "Accountant / Accounts Executive",
        "Accounts Assistant",
        "Billing Executive",
        "Cashier (Office)",
        "Junior Cashier",
        "Petty Cash Coordinator",
        "Payroll Executive",
        "Payroll Assistant",
        "HR Executive",
        "HR Assistant",
        "HR Recruiter (non-technical hiring)",
        "Admin Executive",
        "Office Administrator",
        "Front Office Executive / Receptionist",
        "Reception Supervisor",
        "Document Controller",
        "File Clerk",
        "Data Entry Operator",
        "Back Office Executive",
        "Office Coordinator",
        "Office Assistant / Office Boy",
        "Peon / Messenger",
        "Travel Desk Coordinator",
        "Stationery & Supplies Coordinator",
        "Courier & Dispatch Clerk (Office)",
        "Meeting Room / Facilities Coordinator",
        "Vendor Follow-up Executive (non-technical)",
        "Purchase Coordinator (Office)",
        "Compliance Assistant (internal documentation support)",
        "Attendance & Timesheet Executive"
    ],
    "Customer Support & Call Center": [
        "Customer Support Executive (voice)",
        "Customer Support Executive (non-voice/chat)",
        "Telecaller / Inside Sales Executive",
        "Call Center Agent",
        "Call Center Team Leader",
        "Customer Care Supervisor",
        "Complaint Handling Executive",
        "Escalation Desk Executive",
        "Customer Retention Executive",
        "Feedback / Survey Caller",
        "Appointment Confirmation Caller",
        "Order Confirmation Executive",
        "Service Booking Coordinator",
        "CRM Executive (non-technical)",
        "Helpdesk Coordinator (non-IT)",
        "Reception Call Handler",
        "Front Desk Customer Support",
        "Customer Onboarding Executive (non-technical)"
    ],
    "Sales, Marketing & Field": [
        "Sales Executive (Field)",
        "Sales Executive (Inside)",
        "Business Development Executive (non-IT)",
        "Business Development Manager (non-technical domain)",
        "Sales Coordinator",
        "Sales Support Executive",
        "Lead Generation Executive (non-technical)",
        "Relationship Executive",
        "Relationship Manager (non-technical)",
        "Client Servicing Executive",
        "Account Manager (non-technical service)",
        "Area Sales Executive",
        "Territory Sales Executive",
        "Channel Sales Executive",
        "Distributor Relationship Executive",
        "Merchandiser",
        "Promoter / Brand Promoter",
        "Counter Promoter",
        "Product Demonstrator",
        "Collection Executive",
        "Recovery Executive (field collections)",
        "Market Survey Executive",
        "Marketing Executive (offline)",
        "Event Promoter",
        "Telemarketing Team Leader",
        "Sales Trainer (product/process, non-technical)",
        "Key Accounts Coordinator",
        "Customer Visit Executive"
    ],
    "Operations & Management": [
        "Branch Manager / Unit Manager",
        "Operations Manager",
        "Assistant Operations Manager",
        "Floor Manager / Shift Supervisor",
        "Duty Manager",
        "Team Leader (Operations)",
        "Process Coordinator",
        "Quality Checker (internal operations)",
        "Internal Auditor (operations checks; not statutory audit)",
        "Training Executive (internal)",
        "Trainer (non-technical)",
        "Performance Monitoring Executive",
        "Scheduling & Roster Executive",
        "Workforce Coordinator",
        "Service Supervisor",
        "Site Supervisor (non-technical site ops)",
        "Compliance Supervisor (internal operations)",
        "Customer Experience Manager (non-technical)",
        "Queue Manager (front-end ops)",
        "Operations Executive",
        "Operations Assistant",
        "Control Room Operator (non-IT)"
    ],
    "Logistics, Warehouse, Driver & Delivery": [
        "Driver (Car/Van)",
        "Driver (2-wheeler)",
        "Delivery Executive (company payroll)",
        "Delivery Supervisor",
        "Route Coordinator",
        "Logistics Coordinator",
        "Dispatch Executive",
        "Dispatch Supervisor",
        "Fleet Supervisor",
        "Transport Supervisor",
        "Warehouse Executive",
        "Warehouse Supervisor",
        "Storekeeper",
        "Inventory Controller",
        "Inventory Assistant",
        "Stock Entry Operator",
        "Warehouse Picker",
        "Warehouse Packer",
        "Loading & Unloading Helper",
        "Helper / Loader",
        "Material Handler",
        "Returns Executive",
        "Goods Receiving Assistant (GRN)",
        "Shipping Coordinator",
        "Courier Coordinator",
        "Vehicle Cleaner",
        "Fuel & Trip Sheet Coordinator",
        "Parcel Sorter"
    ],
    "Kitchen, Restaurant & Hospitality": [
        "Chef / Head Chef",
        "Sous Chef",
        "CDP (Chef de Partie)",
        "Commis Chef (Level 1)",
        "Commis Chef (Level 2)",
        "Prep Chef",
        "Tandoor Cook",
        "Grill Cook",
        "Continental Cook",
        "South Indian Cook",
        "North Indian Cook",
        "Bakery Chef (in-house)",
        "Pastry Assistant",
        "Kitchen Helper",
        "Kitchen Supervisor",
        "Kitchen Steward (cleaning)",
        "Dish Washer",
        "Restaurant Manager",
        "Restaurant Supervisor",
        "Captain / Head Waiter",
        "Waiter / Server",
        "Food Runner",
        "Busser (table clearing staff)",
        "Barista",
        "Juice Master",
        "Tea Master",
        "Counter Cashier (Restaurant)",
        "Order Taker",
        "Takeaway Packing Staff",
        "Swiggy/Zomato Order Coordinator",
        "Host / Hostess",
        "Guest Relations Executive (Hospitality)",
        "Housekeeping Staff (Restaurant)",
        "Cleaning Staff (Restaurant)",
        "Store Assistant (Kitchen stores)",
        "Kitchen Inventory Assistant",
        "Kitchen Purchase Runner",
        "Security (Restaurant payroll)",
        "Valet Parking Attendant"
    ],
    "Healthcare, Clinic & Care Staff": [
        "Nurse",
        "Staff Nurse (Day)",
        "Staff Nurse (Night)",
        "Nursing Assistant",
        "Caregiver / Attender",
        "Ward Boy",
        "Aya",
        "Patient Care Assistant",
        "Clinic Receptionist",
        "Clinic Front Office Executive",
        "Appointment Desk Executive",
        "OP Billing Executive (clinic)",
        "Pharmacy Assistant",
        "Pharmacy Billing Executive",
        "Medical Store Helper",
        "Patient Transport Attendant (wheelchair)",
        "Insurance Desk Executive (non-technical)",
        "Medical Records Clerk",
        "Medical File Coordinator",
        "Patient Relations Executive",
        "Cleaning Staff (Clinic)",
        "Security Guard (Clinic)"
    ],
    "Facility Management, Maintenance & Security": [
        "Housekeeping Staff",
        "Housekeeping Supervisor",
        "Cleaner",
        "Janitor",
        "Security Guard",
        "Security Supervisor",
        "Watchman",
        "Gate Keeper",
        "Maintenance Technician (basic)",
        "Electrician (in-house)",
        "Plumber (in-house)",
        "Carpenter (in-house)",
        "Painter (in-house)",
        "AC Technician (in-house)",
        "Lift Operator",
        "Generator Operator",
        "Water Plant Operator (basic)",
        "STP Operator (basic)",
        "Gardening Staff",
        "Gardener Supervisor",
        "Pest Control Staff (on payroll)",
        "Waste Management Attendant",
        "Garbage Collection Staff",
        "Pantry Boy",
        "Tea / Coffee Boy (office pantry)",
        "Office Cook (pantry)",
        "Laundry Attendant",
        "Ironing Staff",
        "Building Caretaker",
        "Fire & Safety Helper (non-technical)"
    ],
    "Retail, Store & Showroom Staff": [
        "Store Manager (Retail)",
        "Assistant Store Manager",
        "Store Supervisor",
        "Salesman / Saleswoman",
        "Counter Sales Executive",
        "Retail Cashier",
        "Stock Boy / Shelf Filler",
        "Visual Merchandising Assistant",
        "Showroom Receptionist",
        "Customer Greeter",
        "Trial Room Attendant",
        "Return Counter Executive",
        "Billing Counter Executive",
        "Stock Auditor (internal store stock checks)",
        "Inventory Clerk (Retail)",
        "Warehouse-to-Store Coordinator",
        "Price Tagging Staff",
        "Packing Staff (Retail)",
        "Gift Wrapping Staff",
        "Store Helper"
    ],
    "Production / Factory / Workshop": [
        "Production Supervisor",
        "Production Executive",
        "Machine Operator",
        "Helper (Production)",
        "Packing Supervisor",
        "Packaging Staff",
        "Line Leader",
        "Assembly Line Worker",
        "Quality Checker (Production)",
        "QC Assistant (Production)",
        "Store & Materials Assistant",
        "Raw Material Handler",
        "Dispatch Helper (Factory)",
        "Forklift Operator",
        "Welding Helper (non-certified helper)",
        "Fabrication Helper",
        "Cutting Operator",
        "Finishing Worker",
        "Fitter Helper",
        "Maintenance Helper",
        "Tool Room Helper",
        "Production Planner Assistant",
        "Shift In-charge",
        "Safety Helper (shop-floor)",
        "Scrap Sorting Staff",
        "Loading Bay Assistant",
        "Housekeeping (Factory floor)",
        "Timekeeper (Factory attendance)"
    ],
    "Education, Training & Institutional Support": [
        "School/Institute Receptionist",
        "Admission Counselor (non-technical)",
        "Fee Collection Cashier",
        "Office Admin (School/Institute)",
        "Library Assistant",
        "Lab Assistant (non-technical support)",
        "Transport Coordinator (School buses)",
        "Attender (School)",
        "Hostel Warden (Male)",
        "Hostel Warden (Female)",
        "Hostel Helper",
        "Campus Security"
    ],
    "Events, Community, Media Support (non-IT)": [
        "Event Coordinator",
        "Event Assistant",
        "Stage Setup Helper",
        "Sound & Light Helper (assistant)",
        "Ticketing Executive",
        "Entry Gate Coordinator",
        "Crowd Management Staff",
        "Usher / Guide",
        "Stall Coordinator",
        "Vendor Coordination Executive (events)",
        "Photo/Video Assistant (non-editor role)",
        "Store & Logistics Assistant (events)"
    ],
    "Beauty Parlour / Salon & Wellness": [
        "Salon Manager",
        "Assistant Salon Manager",
        "Salon Supervisor / Floor In-charge",
        "Front Desk Executive / Receptionist (Salon)",
        "Appointment Coordinator (Salon)",
        "Billing / Cash Counter Executive (Salon)",
        "Customer Relationship Executive (Salon)",
        "Membership / Package Sales Executive",
        "Inventory & Purchase Assistant (Salon)",
        "Storekeeper (Salon products)",
        // Hair Team
        "Hair Stylist (Senior)",
        "Hair Stylist (Junior)",
        "Hairdresser",
        "Hair Colorist",
        "Hair Treatment Specialist (Keratin/Smoothening)",
        "Hair Spa Therapist",
        "Blow Dry Specialist",
        "Barber (Men’s grooming)",
        "Kids Haircut Specialist",
        "Shampoo Assistant / Hair Wash Assistant",
        // Skin & Facial Team
        "Beautician (Senior)",
        "Beautician (Junior)",
        "Facial Therapist",
        "Skin Care Specialist",
        "Cleanup / Facial Assistant",
        "Bleach & Detan Specialist",
        "Threading Specialist",
        "Waxing Specialist",
        "Body Polishing Therapist",
        "Body Spa Therapist",
        // Nail Team
        "Nail Technician",
        "Nail Artist",
        "Manicurist",
        "Pedicurist",
        // Bridal & Makeup Team
        "Makeup Artist (Senior)",
        "Makeup Artist (Junior)",
        "Bridal Makeup Specialist",
        "Saree Drapist",
        "Mehandi Artist (on payroll)",
        "Lash & Brow Technician",
        // Spa & Wellness
        "Massage Therapist (Spa)",
        "Steam & Sauna Attendant (if available)",
        "Ayurveda / Wellness Assistant (non-medical)",
        // Support Staff
        "Salon Helper / Assistant",
        "Towel & Laundry Attendant",
        "Housekeeping / Cleaning Staff (Salon)",
        "Pantry / Refreshments Staff",
        "Security Guard (Salon)",
        "Valet / Parking Attendant (Salon)",
        "Runner / Errand Staff (Salon)"
    ]
};
